stages:
  training_and_prediction_service:
    cmd: python app.py
    deps:
    - app.py
    - Training_Batch_Files
    - src/Training_Service/Data_Preprocessing/preprocessing.py
    - src/Training_Service/Data_Validation/Data_Validation.py
    - src/Training_Service/db/db_operations.py
    - src/logger/logger.py
    - schema_training.json
    - src/Training_Service/Cluster_Data/cluster.py
    - src/Training_Service/model_operations/model_ops.py
    - src/Training_Service/metrics/metrics.py
    - src/Training_Service/Hyperparameter/hyperparameter_tunning.py
    - Prediction_Batch_files
    - src/Prediction_Service/Data_Validation/Prediction_Data_Validation.py
    - schema_prediction.json