data_preprocessing:
  csv_path: Master_Training_File/Zomato.csv
  columns_to_remove: ['serial','url','address' ,'phone', 'reviews_list','dish_liked']
  n_neighbors: 3
  rename_columns: {'listed_in_type':'type','listed_in_city':'city','approx_cost_for_two_people':'cost'}
  columns_to_dummy_variables: ['location','name','rest_type','cuisines','menu_item','online_order','book_table','type','city']
  drop_first: True
  alpha: 0.005 # for lasso feature selection
  train_test_split:
    test_size: 0.2
    random_state: 42
hyperparameter_tunning:
  xgboost_hyperparameters: 
    # Parameters that we want to pass
    parameters: {                        
        'num_boost_round': [10, 25, 50],
        'eta': [0.05, 0.1, 0.3],
        'max_depth': [3, 4, 5],
        'subsample': [0.9, 1.0],
        'colsample_bytree': [0.9, 1.0],
          }
    GridSearchCV:
      cv: 5
      verbose: 3
    RandomizedSearchCV:
      cv: 5
      verbose: 3
  random_forest_hyperparameters: 
    # Parameters that we want to pass
    parameters: { 
          'n_estimators': [200, 500],
          'max_features': ['auto', 'sqrt', 'log2'],
          'max_depth' : [4,5,6,7,8],
          }
    GridSearchCV:
      cv: 5
      verbose: 3
    RandomizedSearchCV:
      cv: 5
      verbose: 3

